# Generated by Django 3.2 on 2022-11-29 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазин'},
        ),
        migrations.AlterField(
            model_name='sale',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Картирнка'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sale.shop', verbose_name='Магаазин'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Em@il'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='website',
            field=models.CharField(max_length=100, verbose_name='Вебсайт'),
        ),
    ]
